# -*- coding: utf-8 -*-
"""Manual-inference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b-O_t5f6Pjf_fTeBU5j10wyLZz7ngy2s
"""

#@markdown
from IPython.display import clear_output
from google.colab import drive
drive.mount('/content/gdrive')
clear_output()

#@markdown Dependencies

!git clone https://github.com/CompVis/stable-diffusion.git/

!apt-get --yes install cuda-toolkit-11-3
!pip install pytorch==1.11.0
!pip install torchvision==0.12.0
#!pip install numpy==1.19.2
!pip install numpy==1.2
!pip install albumentations==0.4.3
!pip install diffusers
!pip install opencv-python==4.1.2.30
!pip install pudb==2019.2
!pip install invisible-watermark
!pip install imageio==2.9.0
!pip install imageio-ffmpeg==0.4.2
!pip install pytorch-lightning==1.4.2
!pip install omegaconf==2.1.1
!pip install test-tube>=0.7.5
!pip install streamlit>=0.73.1
!pip install einops==0.3.0
!pip install torch-fidelity==0.3.0
!pip install transformers==4.19.2
!pip install torchmetrics==0.6.0
!pip install kornia==0.6

weights = "/content/gdrive/Shareddrives/TFG-Oier-Mentxaka/Fast-Dreambooth/Sessions/Biscuit20230117/Biscuit20230117.ckpt"
!python stable-diffusion/scripts/txt2img.py --prompt "a Biscuit20230117" --plms --ckpt $weights --skip_grid --n_samples 1